[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
gitat-core = { path = "crates/gitat-core" }
gitat-ui = { path = "crates/gitat-ui" }
thiserror = "2"
anyhow = "1"
ratatui = "0.30.0"
crossterm = "0.28"
similar = "2"
insta = "1.47.2"
