[package]
name = "gitat"
version.workspace = true
edition.workspace = true

[dependencies]
gitat-core = { workspace = true }
gitat-ui = { workspace = true }
anyhow = { workspace = true }
crossterm = { workspace = true }
ratatui = { workspace = true }
tokio = { workspace = true }
notify = { workspace = true }
notify-debouncer-full = { workspace = true }
